// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdz0kgqexf7ZMLMYGnILmly3Siq8RPXSg',
    appId: '1:306995604877:web:095680ff8074cc5dda21c4',
    messagingSenderId: '306995604877',
    projectId: 'epaddy-defab',
    authDomain: 'epaddy-defab.firebaseapp.com',
    databaseURL: 'https://epaddy-defab-default-rtdb.firebaseio.com',
    storageBucket: 'epaddy-defab.firebasestorage.app',
    measurementId: 'G-NPLZNTYSS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdi1DVIbligiLbYQbxxDqKfAPtHnjpoqg',
    appId: '1:306995604877:android:17f16382b7822a2dda21c4',
    messagingSenderId: '306995604877',
    projectId: 'epaddy-defab',
    databaseURL: 'https://epaddy-defab-default-rtdb.firebaseio.com',
    storageBucket: 'epaddy-defab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP9JpkHAGbEiHg4uzgCpWzy8Mt0sM9JkU',
    appId: '1:306995604877:ios:688282b8b816d20dda21c4',
    messagingSenderId: '306995604877',
    projectId: 'epaddy-defab',
    databaseURL: 'https://epaddy-defab-default-rtdb.firebaseio.com',
    storageBucket: 'epaddy-defab.firebasestorage.app',
    iosBundleId: 'com.example.epaddyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP9JpkHAGbEiHg4uzgCpWzy8Mt0sM9JkU',
    appId: '1:306995604877:ios:688282b8b816d20dda21c4',
    messagingSenderId: '306995604877',
    projectId: 'epaddy-defab',
    databaseURL: 'https://epaddy-defab-default-rtdb.firebaseio.com',
    storageBucket: 'epaddy-defab.firebasestorage.app',
    iosBundleId: 'com.example.epaddyMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdz0kgqexf7ZMLMYGnILmly3Siq8RPXSg',
    appId: '1:306995604877:web:7ccbe9fda65c846eda21c4',
    messagingSenderId: '306995604877',
    projectId: 'epaddy-defab',
    authDomain: 'epaddy-defab.firebaseapp.com',
    databaseURL: 'https://epaddy-defab-default-rtdb.firebaseio.com',
    storageBucket: 'epaddy-defab.firebasestorage.app',
    measurementId: 'G-43ZYCJKMB3',
  );
}
